### ISSUE TITLE
Add sha256sum as list of Prerequisites and limit Terraform version to 11 

### ISSUE THREAD

**Issue by diegopeleteiro** [moritzheiber/gocd-kickstarter#1]
sha256sum is not part of standard MacOS installation.

The GoCD provider does not support the automatic upgrading to 0.12, thus the Terraform version should be locked below 0.12.

**Comment by moritzheiber** [comment]
@diegopeleteiro As discussed yesterday, I believe macOS, natively without having to install any support tools, has a command called `shasum`, which I think is an almost exact replica of `sha256sum`? I don't have access to a Mac right now, so you would have to confirm. According to this article the correct command should be `shasum -a 256 <file>` to calculate a checksum and possibly `echo "<checksum>  file" | shasum -a 256 -` to verify (mind the two space after the checksum!).
 
As for Terraform 0.12, it should be compatible with "old" Terraform definitions and plugins, as such, it should run the definitions, using the plugin, just fine. You cannot write Terraform 0.12 definitions using it though, but the documentation doesn't say so though. I wouldn't classify this as an issue necessarily? But you could adjust the README accordingly and add a short disclaimer to make this visible.

**Comment by moritzheiber** [comment]
I've pinned the version to `"< 0.12"` for now. I'm also in contact with the plugin authors to make sure we're going to see a compatible version in the near future :+1:
